Update Vanilla inclusion method to use NPM3 method
ubuntudesign/vanilla-docs-theme pull request #23
Opened 2016-09-15 09:24 UTC by barrymcgee

As detailed https://github.com/ubuntudesign/vanilla-framework/issues/470

Fixes #10

2016-09-15 09:30 UTC, barrymcgee commented
@robin Your note on original ticket states - "However, when the new version for a theme is published, no site will be able to use the new version until it updates its build system to use NPM3 and set up the sass include path correctly."

Is it correct to say this should not be merged until you or @WillMoggridge tweak the build?

2016-09-15 20:32 UTC, nottrobin commented
@barrymcgee It is fine (and I would say, encouraged) to publish this change as long as you do it with at least a minor version change (e.g. `1.1.2` -> `1.2.0`) to signify an API change. As each site should be locked to the specific version of the theme, this won't break anything.

It is then up to any sites using the theme to change to support this new model before they upgrade to this new version of the theme.

`docs-vanilla-theme` is one of the safest anyway - it's only used by `maas.io/docs` currently.

2016-09-15 20:37 UTC, nottrobin commented on gulpfile.js
> +// ../ is here just for reference.
I don't understand what this means. Why do we need `../`?

2016-09-15 20:54 UTC, nottrobin commented on gulpfile.js
> +            includePaths: ['scss'].concat(sassImportPaths)
`'scss'` doesn't appear to be required. So why not simply `includePaths: 'node_modules'`?

2016-09-15 20:54 UTC, nottrobin commented
Let me know when this is ready for review.

2016-09-15 20:59 UTC, barrymcgee commented
Gotcha - in that case, this is ready for review.

On Thu, Sep 15, 2016 at 21:54 Robin Winslow

<
mailto:Robin Winslow <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Let me know when this is ready for review.

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/ubuntudesign/docs-vanilla-theme/pull/23#issuecomment-247452639
, or
https://github.com/notifications/unsubscribe-auth/AAe24uMl1A77hPZGLiHknmIXxEPRVpSjks5qqbCTgaJpZM4J9qTz
.

2016-09-15 21:03 UTC, nottrobin requested changes
I get an error if I do `gulp watch` and then trigger a build by touching a file. I think `watch`needs similar treatment to `sass`.

2016-09-15 21:20 UTC, barrymcgee commented on gulpfile.js
> +// ../ is here just for reference.
I copied over the change from the ubuntu-vanilla-theme update you referenced, if not needed, I'll remove - https://github.com/ubuntudesign/ubuntu-vanilla-theme/commit/da0da7657135dc05b5a05063440367b66118a345

2016-09-15 21:24 UTC, nottrobin commented on gulpfile.js
> +// ../ is here just for reference.
Ah I see. So it came from @deshack. I don't think it is necessary, please remove it unless you can think of a reason for it to stay. It should ideally be removed from ubuntu-vanilla-theme too, but that's hardly urgent.

2016-09-15 21:47 UTC, deshack commented on gulpfile.js
> +// ../ is here just for reference.
Sorry guys, I don't really know why I included the `../`. It can be safely removed.

2016-09-15 21:59 UTC, deshack commented on gulpfile.js
> +            includePaths: ['scss'].concat(sassImportPaths)
@nottrobin This can be removed too, since all `@import`s are relative to the current file. It represents a layer of security, though, since it ensures that the current library's sass files are among the import paths.

2016-09-15 22:04 UTC, nottrobin commented on gulpfile.js
> +            includePaths: ['scss'].concat(sassImportPaths)
@deshack could you explain that a bit more for me? How does including the current library's files in the sass path help increase security? Since relative imports will continue to work either way.

2016-09-15 22:14 UTC, deshack commented on gulpfile.js
> +            includePaths: ['scss'].concat(sassImportPaths)
@nottrobin there have been issues in the past with relative imports, that's all. Now it should be pretty stable and safe to rely on relative imports, so yes, you can remove this too.

2016-09-16 10:45 UTC, barrymcgee commented
@nottrobin Ready for review again..

2016-09-16 10:48 UTC, nottrobin commented
Thanks @barrymcgee, code looks good.

You just need to fix `gulp watch` now:

``` bash
gulp watch
[11:47:12] Using gulpfile ~/git-projects/docs-vanilla-theme/gulpfile.js
[11:47:12] Starting 'watch'...
[11:47:12] Finished 'watch' after 30 ms
[11:47:23] Starting 'sass-lite'...

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: scss/_theme.scss
Error: File to import not found or unreadable: vanilla-framework/scss/vanilla
       Parent style sheet: /home/robin/git-projects/docs-vanilla-theme/scss/_theme.scss
        on line 2 of scss/_theme.scss
>> @import 'vanilla-framework/scss/vanilla';
   ^

    at options.error (/home/robin/git-projects/docs-vanilla-theme/node_modules/node-sass/lib/index.js:272:32)
```

2016-09-16 10:53 UTC, nottrobin requested changes
Please get `gulp watch` working.

2016-09-16 10:53 UTC, nottrobin approved these changes

2016-09-16 10:54 UTC, nottrobin requested changes
Please get gulp watch working.

2016-09-16 11:06 UTC, deshack commented
`sassdoc` devDependency is missing from the `package.json`:

```
▶ gulp watch
module.js:328
    throw err;
    ^

Error: Cannot find module 'sassdoc'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/deshack/projects/ubuntu/docs-vanilla-theme/gulpfile.js:9:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
```

2016-09-16 12:07 UTC, barrymcgee commented
@deshack Thanks for flagging that. We're no longer using sassdoc so I've removed the dep from package.json.

This PR should hopefully be all working now, sorry for confusion.

2016-09-16 15:26 UTC, nottrobin approved these changes

2016-09-16 15:26 UTC, merged